---
Name: 'amp-pages'
---
SilverStripe\CMS\Model\SiteTree:
  extensions:
    - DorsetDigital\SilverStripeAmpPages\AmpPagesSiteTreeExtension
    
SilverStripe\CMS\Controllers\ContentController:
  extensions:
    - DorsetDigital\SilverStripeAmpPages\AmpPagesControllerExtension
    
SilverStripe\View\Requirements:
  extensions:
    - DorsetDigital\SilverStripeAmpPages\AmpPagesRequirementsExtension
    